# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Dangerous Data
tagline:             'Robert Danger Winters'
description:         'The blog of Rob Winters, Data Nerd'
url:                 http://wintersrd.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Rob Winters
  url:               https://nl.linkedin.com/wintersrd/en
  email:             wintersrd@gmail.com

# Custom vars
version:             1.0.0
