# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Dangerous Data'
tagline:          'The Blog of Rob Danger Winters'
url:              http://wintersrd.github.io
paginate:         1
baseurl:          /
author:
  name:           Rob Winters
  url:            https://nl.linkedin.com/wintersrd/en
  email:          wintersrd@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/wintersrd/wintersrd.github.io
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
