    # Dependencies
markdown:            redcarpet
highlighter:         pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'Robert D Winters'
tagline:             'Experienced BI Practitioner'
description:         'The blog of Rob Winters'
url:                 http://robertwinters.nl
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Rob Winters
  url:               https://nl.linkedin.com/wintersrd/en
  email:             wintersrd@gmail.com

# Custom vars
version:             1.0.0
