baseurl = "http://robertwinters.nl"
languageCode = "en-us"
title = "Robert Winters"
theme = "hyde"
copyright = "Rob Winters"

[Author]
	name = "Rob Winters"

[Permalinks]
	blog = "/:year/:month/:filename/"
	code = "/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "BI Practitioner"
	github = "https://github.com/wintersrd"
	disqus = "wintersrd"

